a = input("Tell me a verb - ending in ing ")
b = input("Tell me a place ")
c = input("adverb ")
d = input("Tell me an adjective ")
e = input("sport equipment(singular) ")
f = input("verb ")
g = input("place ")
h = input("noun ")
i = input("adjective ")
j = input("verb ")
k = input("adjective ")
l = input("noun ")
print(f"I like {a} in the {b} with a {c} {d} {e}. I would {f} in the {g}, but the {h} is {i}, so now I have to {j} in the park with a {k} {l}. ")
